import type { Metadata } from 'next'
import Script from 'next/script'

import { Open_Sans } from 'next/font/google'
import { Oxanium } from 'next/font/google'

import './globals.css'
import '@webbdeveloper/webb-css/dist/index.css'

import Header from './components/Header'
import Footer from './components/Footer'

const openSans = Open_Sans({
  subsets: ['latin',],
  variable: '--font-open-sans',
})

const oxanium = Oxanium({
  subsets: ['latin',],
  variable: '--font-oxanium',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`
          ${openSans.variable} ${oxanium.variable}
          flex flex-col
          md:p-8
          p-4
          min-h-screen
          w-full
          justify-between
        `}
      >
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
